snapshot: lts-22.21 # GHC 9.6.5

docker:
  enable: false
  repo: quay.io/benz0li/ghc-musl:9.6.5

nix:
  # --nix on the command-line to enable.
  packages:
  - zlib
  - unzip

flags:
  stack:
    developer-mode: true
